export const PHYSICS_CONSTANTS = {
  GRAVITY: -9.81,
  MAX_VELOCITY: 15,
  MIN_VELOCITY: 0.1,
  BALL_RADIUS: 0.5,
  BALL_MASS: 1,
  BALL_RESTITUTION: 0.85,
  AIR_RESISTANCE: 0.98,
  ROLLING_FRICTION: 0.995,
  COLLISION_DAMPING: 0.05,
  FORCE_ACCUMULATION_THRESHOLD: 0.001,
  ENERGY_CONSERVATION_FACTOR: 0.98
} as const;

export const SIMULATION_CONSTANTS = {
  MIN_SPACING: 5,
  MAX_PRIMITIVES: 50,
  SPAWN_RADIUS: 100,
  CLEANUP_RADIUS: 150,
  ANIMATION_DURATION: 2,
  FADE_DURATION: 1,
  MAX_TRAIL_LENGTH: 100,
  FORCE_INTEGRATION_STEPS: 4
} as const;