export const PHYSICS_CONSTANTS = {
  GRAVITY: -9.81,
  MAX_VELOCITY: 10,
  BALL_RADIUS: 0.5,
  BALL_MASS: 1,
  BALL_RESTITUTION: 0.8,
  VELOCITY_REDUCTION: 0.85,
  COLLISION_DAMPING: 0.15
} as const;

export const SIMULATION_CONSTANTS = {
  MIN_SPACING: 5,
  MAX_PRIMITIVES: 50,
  SPAWN_RADIUS: 100,
  CLEANUP_RADIUS: 150,
  ANIMATION_DURATION: 2,
  FADE_DURATION: 1,
  MAX_TRAIL_LENGTH: 100
} as const;